# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 838)
        MainWindow.setStyleSheet("color:white;\n"
"background: rgb(29, 29, 29)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.title_edit.setGeometry(QtCore.QRect(10, 20, 681, 51))
        self.title_edit.setText("")
        self.title_edit.setObjectName("title_edit")
        self.text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.text_edit.setGeometry(QtCore.QRect(10, 90, 681, 691))
        self.text_edit.setObjectName("text_edit")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(720, 30, 331, 251))
        self.listWidget.setObjectName("listWidget")
        self.creare_btn = QtWidgets.QPushButton(self.centralwidget)
        self.creare_btn.setGeometry(QtCore.QRect(740, 290, 141, 28))
        self.creare_btn.setStyleSheet("border: 2px solid white;\n"
"border-radius: 10px;\n"
"text-align: center;\n"
"background: rgb(255, 189, 82)")
        self.creare_btn.setObjectName("creare_btn")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(890, 290, 141, 28))
        self.delete_btn.setStyleSheet("border: 2px solid white;\n"
"border-radius: 10px;\n"
"text-align: center;\n"
"background: rgb(255, 189, 82)")
        self.delete_btn.setObjectName("delete_btn")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(770, 330, 251, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(720, 400, 341, 192))
        self.listWidget_2.setObjectName("listWidget_2")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(770, 330, 251, 28))
        self.save_btn.setStyleSheet("border: 2px solid white;\n"
"border-radius: 10px;\n"
"text-align: center;\n"
"background: rgb(255, 189, 82)")
        self.save_btn.setObjectName("save_btn")
        self.vikno_zamit = QtWidgets.QListWidget(self.centralwidget)
        self.vikno_zamit.setGeometry(QtCore.QRect(720, 30, 331, 251))
        self.vikno_zamit.setObjectName("vikno_zamit")
        self.add_teg = QtWidgets.QPushButton(self.centralwidget)
        self.add_teg.setGeometry(QtCore.QRect(700, 640, 251, 28))
        self.add_teg.setStyleSheet("border: 2px solid white;\n"
"border-radius: 10px;\n"
"text-align: center;\n"
"background: rgb(255, 189, 82)")
        self.add_teg.setObjectName("add_teg")
        self.searck_teg = QtWidgets.QPushButton(self.centralwidget)
        self.searck_teg.setGeometry(QtCore.QRect(960, 600, 101, 21))
        self.searck_teg.setStyleSheet("border: 2px solid white;\n"
"border-radius: 10px;\n"
"text-align: center;\n"
"background: rgb(255, 189, 82)")
        self.searck_teg.setObjectName("searck_teg")
        self.tag_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.tag_edit.setGeometry(QtCore.QRect(720, 600, 231, 22))
        self.tag_edit.setText("")
        self.tag_edit.setObjectName("tag_edit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(720, 380, 73, 16))
        self.label.setObjectName("label")
        self.delete_teg = QtWidgets.QPushButton(self.centralwidget)
        self.delete_teg.setGeometry(QtCore.QRect(810, 680, 251, 28))
        self.delete_teg.setStyleSheet("border: 2px solid white;\n"
"border-radius: 10px;\n"
"text-align: center;\n"
"background: rgb(255, 189, 82)")
        self.delete_teg.setObjectName("delete_teg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EasyEditor"))
        self.creare_btn.setText(_translate("MainWindow", "Створити замітку"))
        self.delete_btn.setText(_translate("MainWindow", "Видалити замітку"))
        self.pushButton_3.setText(_translate("MainWindow", "Зберегти зімтку"))
        self.save_btn.setText(_translate("MainWindow", "Зберегти зімтку"))
        self.add_teg.setText(_translate("MainWindow", "Додати тег"))
        self.searck_teg.setText(_translate("MainWindow", "Шукати тег"))
        self.tag_edit.setPlaceholderText(_translate("MainWindow", "Введіть назву тегу"))
        self.label.setText(_translate("MainWindow", "Список тегів"))
        self.delete_teg.setText(_translate("MainWindow", "Видалити тег"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
